spring.application.name=paprueba
spring.datasource.url=jdbc:postgresql://localhost:5432/eventhub2026
spring.datasource.username=TU_USUARIO
spring.datasource.password=TU_CONTRASEÑA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=eventhub2026
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=9090
